name: Lint and run test

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout git branch
      - uses: actions/checkout@v2
      # Install node.js environment
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      # Cache node_modules (busting only when yarn.lock change)
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      # Install dependencies
      - name: Install
        run: yarn install --frozen-lockfile --silent
      # Run eslint
      - name: Lint
        run: yarn run lint

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        node-version: [
            16.x, # current LTS
          ]
    steps:
      # Checkout git branch
      - uses: actions/checkout@v2
      # Install node.js environment
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      # Cache node_modules (busting only when yarn.lock change)
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      # Install dependencies
      - name: Install
        run: yarn install --frozen-lockfile --silent
      # Run all tests
      - name: Test
        run: yarn run test --ci --coverage
